### ISSUE TITLE
Error: Impossible to launch the application

### ISSUE THREAD

**Issue by luisfpinto** [netbeast/node-red#4]
When I try to run node-red on the dashboard I get this error. I can run the application without the dashboard but not on it.

```
Exception in routes stack:
Error: Impossible to launch the application
    at keepTrying (C:\Users\Administrator\Desktop\dashboard\src\models\activity.js:65:38)
    at Timer.listOnTimeout (timers.js:92:15)
POST /api/activities/node-red 405 71152.161 ms - 36
```

Please check this out in order to solve the problem and allow the app run on the dashboard

**Comment by Joncy** [comment]
When launching on cloud dashboard i get:

Failed to load resource: the server responded with a status of 405 (Method Not Allowed) 

Refferring to http://dashboard.netbeast.co/api/activities/node-red

**Comment by jsdario** [comment]
Can you please take a look deeper? does the log say something in particular about `node-red`? can you run `node-red` standalone (without Netbeast)?

**Comment by luisfpinto** [comment]
I will take care of this issue from now on. I really want this issue to be fixed as soon as possible 🎢

**Comment by luisfpinto** [comment]
Problem fixed. Now it runs on the dashboard 🎉  .

However, there is a problem when node-red is running inside de dashboard with the styles. Can anyone help me with this? I don't really know what is going in with this.
